services:
  porkbun-ddns:
    image: "mietzen/porkbun-ddns:latest"
    container_name: porkbun-ddns
    environment:
      DOMAIN: "nuv.sh" # Your Porkbun domain
      SUBDOMAINS: "git,draw,portainer,ci,pdf,matrix,chat"
      SECRETAPIKEY: "${API_SECRET}" # Your Porkbun Secret-API-Key
      APIKEY: "${API_KEY}" # Your Porkbun API-Key
    restart: unless-stopped
