services:
    homeserver:
        image: matrixconduit/matrix-conduit:latest
        ### If you want to build a fresh image from the sources, then comment the image line and uncomment the
        ### build lines. If you want meaningful labels in your built Conduit image, you should run docker compose like this:
        ### CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ') VERSION=$(grep -m1 -o '[0-9].[0-9].[0-9]' Cargo.toml) docker compose up -d
        # build:
        #     context: .
        #     args:
        #         CREATED: '2021-03-16T08:18:27Z'
        #         VERSION: '0.1.0'
        #         LOCAL: 'false'
        #         GIT_REF: origin/master
        container_name: conduit
        restart: unless-stopped
        volumes:
            - db:/var/lib/matrix-conduit/
        environment:
            CONDUIT_SERVER_NAME: nuv.sh # EDIT THIS
            CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
            CONDUIT_DATABASE_BACKEND: rocksdb
            CONDUIT_PORT: 6167
            CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
            CONDUIT_ALLOW_REGISTRATION: 'true'
            CONDUIT_REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
            CONDUIT_ALLOW_FEDERATION: 'true'
            CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
            CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
            #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
            CONDUIT_ADDRESS: 0.0.0.0
            CONDUIT_CONFIG: '' # Ignore this
        networks:
          - proxy
        labels:
          caddy_0: matrix.nuv.sh
          caddy_0.reverse_proxy: "{{upstreams 6167}}"
          caddy_0.tls.dns: "porkbun"
          caddy_0.tls.dns.api_key: "${API_KEY}"
          caddy_0.tls.dns.api_secret_key: "${API_SECRET}"
          caddy_0.tls.resolvers: "1.1.1.1"
          caddy_1: nuv.sh
          caddy_1.0_respond: '/.well-known/matrix/server "{ \"m.server\": \"matrix.nuv.sh:443\" }"'
          caddy_1.1_respond: '/.well-known/matrix/client "{ \"m.homeserver\": \"matrix.nuv.sh:443\" }"'
          caddy_1.2_respond: '/.well-known/discord "dh=023d0b537a304733396fb55473914402092b66dc'

    #mautrix-discord:
    #  container_name: mautrix-discord
    #  image: dock.mau.dev/mautrix/discord:<version>
    #  restart: unless-stopped
    #  volumes:
    #  - ./mautrix-discord:/data
     
      
    #element-web:
      #image: vectorim/element-web:latest
      #restart: unless-stopped
      #volumes:
        #- ./element_config.json:/app/config.json
      #depends_on:
        #- homeserver
      #networks: 
        #- proxy
      #labels:
        #caddy: chat.nuv.systems
        #caddy.reverse_proxy: "{{upstreams 80}}"
        #caddy.tls.dns: "ionos ${API_Key}"
        #caddy.tls.resolvers: "1.1.1.1"


volumes:
    db:

networks:
  proxy:
    external: true
