services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config 
      - ./config:/etc/caddy
      - /srv:/srv
    env_file: ".env"
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: "/etc/caddy/CADDYFILE"
      CADDY_DOCKER_ENV_FILE: "/etc/caddy/.env"
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    name: proxy
    driver: bridge
