networks:
  proxy:
    external: true

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    env_file: .env
    user: 1000:1000 # should be owner of volumes
    volumes:
      - ./data:/data
      - /home/liv/Media/Audio/Music:/music:ro
    labels:
      caddy_0: tunes.nuv.sh
      caddy_0.reverse_proxy: "{{upstreams 4533}}"
      caddy_1: tunes.ollie.earth
      caddy_1.reverse_proxy: "{{upstreams 4533}}"
    networks:
      - proxy 
