volumes: 
  grafana-storage:
networks:
  proxy:
    external: true

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.nuv.sh/
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - proxy
    labels:
      caddy_0: grafana.nuv.sh
      caddy_0.reverse_proxy: "{{upstreams 3000}}"
      caddy_0.tls.dns: "porkbun"
      caddy_0.tls.dns.api_key: "${API_KEY}"
      caddy_0.tls.dns.api_secret_key: "${API_SECRET}"
      caddy_0.tls.resolvers: "1.1.1.1"
