volumes:
  atuin_db:
  atuin_config:

networks:
  proxy: 
    external: true
  atuin:


services:
  atuin:
    container_name: atuin_server
    restart: always
    image: ghcr.io/atuinsh/atuin:v18.8.0
    command: server start
    volumes:
      - atuin_config:/config
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@db/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
    depends_on:
      - db
    networks:
      - atuin
      - proxy
    labels:
      caddy_0: atuin.nuv.sh
      caddy_0.reverse_proxy: "{{upstreams 8888}}"
      caddy_0.tls.dns: "porkbun"
      caddy_0.tls.dns.api_key: "${API_KEY}"
      caddy_0.tls.dns.api_secret_key: "${API_SECRET}"
      caddy_0.tls.resolvers: "1.1.1.1"

  db:
    image: postgres:14
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - atuin_db:/var/lib/postgresql/data/
    networks:
      - atuin
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
