services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - data:/usr/share/tessdata # Required for extra OCR languages
      - data:/configs
      - data:/customFiles/
      - data:/logs/
      - data:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    networks:
      - proxy
    labels:
      caddy: pdf.nuv.systems
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls.dns: "ionos ${API_Key}"
      caddy.tls.resolvers: "1.1.1.1"

volumes: 
  data:

networks:
  proxy:
    external: true
